# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28e3764649d73bbd34c72b174f46cc607062cb14feb09e6f45b12ad0d7854c8242d3879eb33ca98eaa7321e14d29b07e8db0e61fcf4f9761ba1ae5329926a580

test:
  secret_key_base: 8807376ac628a7eca01178760e74b1b880e57bcef43a62ef52ce6bb2b1f7b8176ee4d41fe5950092b26d59826ae2c7c590c75c65c0ac631603987760400ff19d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
